import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "@/components/banner";
import { Lora, Inter } from "next/font/google";
import Header from "@/components/Layout/Header/Header";
import { InfoProvider } from "@/context/InfoContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // các trọng số muốn dùng
  variable: "--font-inter", // tạo biến CSS để dùng trong globals.css hoặc tailwind
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // các trọng số muốn dùng
  variable: "--font-lora", // tạo biến CSS để dùng trong globals.css hoặc tailwind
});

export const metadata: Metadata = {
  title: "MDD Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lora.variable} ${inter.variable}`}>
      <body className={`antialiased`}>
        <ToastContainer position="top-right" autoClose={3000} />
        <InfoProvider>
          <Header />
          <Banner />
          {children}
          <footer className="flex items-center justify-center h-[46px] bg-[#f4f4f4]">
            <p className="text-[15px] font-normal">
              Copyright © 2024 My MDD Diary
            </p>
          </footer>
        </InfoProvider>
      </body>
    </html>
  );
}
